26-27-2019 00:27:07 15Scends:INFO:部分数据预览如下：
26-27-2019 00:27:07 15Scends:INFO:[['2435435', nan], ['34534543', 'S-1'], ['369433311633', 'S-2']]
26-27-2019 00:27:07 15Scends:INFO:2435435 不是顺丰单号
26-27-2019 00:27:07 15Scends:INFO:34534543 不是顺丰单号
26-27-2019 00:27:07 15Scends:INFO:已成功加载18个顺丰快递单号
26-27-2019 00:27:07 15Scends:INFO:请在60秒内用手机完成微信扫码，超时后会视同不扫码继续运行
26-27-2019 00:27:07 15Scends:INFO:可以不使用对应手机号的微信扫码，但是将无法获得电子存根信息
26-27-2019 00:27:07 15Scends:INFO:成功扫码之后可以将二维码图片关闭
26-27-2019 00:27:07 15Scends:INFO:正在打开微信扫码界面・・・

26-27-2019 00:27:33 15Scends:INFO:当前进度：1/18
26-27-2019 00:27:33 15Scends:INFO:正在查询的物流单号：369433311633
26-27-2019 00:27:33 15Scends:INFO:正在输入单号进行查询
26-27-2019 00:27:39 15Scends:INFO:尝试解析滑动验证码
26-27-2019 00:27:42 15Scends:INFO:解析成功，正在模拟滑动验证码・・・
26-27-2019 00:27:53 15Scends:INFO:尝试刷新验证码
26-27-2019 00:27:54 15Scends:INFO:尝试解析滑动验证码
26-27-2019 00:27:55 15Scends:INFO:解析成功，正在模拟滑动验证码・・・
26-28-2019 00:28:06 15Scends:INFO:尝试刷新验证码
26-28-2019 00:28:08 15Scends:INFO:尝试解析滑动验证码
26-28-2019 00:28:09 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 280, in get_verify_img
    img = self.browser.find_element_by_xpath('//img[@id="slideBkg"]')
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: TypeError: can't access dead object

26-28-2019 00:28:09 15Scends:INFO:解析成功，正在模拟滑动验证码・・・
26-28-2019 00:28:09 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 152, in __reload_verify_img
    self.move_slider()
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 337, in move_slider
    '//div[@id="tcaptcha_drag_button"]')
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: TypeError: can't access dead object

26-28-2019 00:28:11 15Scends:INFO:获取物流节点信息和截图
26-28-2019 00:28:12 15Scends:INFO:正在获取电子存单信息和截图
26-28-2019 00:28:12 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 398, in get_dzcg_info
    '//div[@class="operates-wrapper"]/a').click()
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="operates-wrapper"]/a

26-28-2019 00:28:13 15Scends:INFO:该单号对应的手机号与扫码的微信号可能不符，无法获取电子存根截图
26-28-2019 00:28:13 15Scends:INFO:正在为截图添加水印
26-28-2019 00:28:13 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 422, in add_watermark
    self.__watermark(self.screenshot_img2)
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 115, in __watermark
    im = Image.open(imageFile)
  File "C:\Program Files\Python36\lib\site-packages\PIL\Image.py", line 2634, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\python_wwcheng\\sf_express\\Output\\2019-07-26 00-27-07\\img\\1-dzcg-369433311633.png'
26-28-2019 00:28:13 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 430, in next_bill_number
    '//button[@class="close"]').click()
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //button[@class="close"]

26-28-2019 00:28:15 15Scends:INFO:单号 369433311633  用时 41.51931548118591秒
26-28-2019 00:28:15 15Scends:INFO:将物流节点和电子存根信息写入csv

26-28-2019 00:28:15 15Scends:INFO:当前进度：2/18
26-28-2019 00:28:15 15Scends:INFO:正在查询的物流单号：233679804279
26-28-2019 00:28:15 15Scends:INFO:正在输入单号进行查询
26-28-2019 00:28:21 15Scends:INFO:尝试解析滑动验证码
26-28-2019 00:28:23 15Scends:INFO:解析成功，正在模拟滑动验证码・・・
26-28-2019 00:28:34 15Scends:INFO:尝试刷新验证码
26-28-2019 00:28:36 15Scends:INFO:尝试解析滑动验证码
26-28-2019 00:28:37 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 280, in get_verify_img
    img = self.browser.find_element_by_xpath('//img[@id="slideBkg"]')
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: TypeError: can't access dead object

26-28-2019 00:28:38 15Scends:INFO:解析成功，正在模拟滑动验证码・・・
26-28-2019 00:28:38 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 152, in __reload_verify_img
    self.move_slider()
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 337, in move_slider
    '//div[@id="tcaptcha_drag_button"]')
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: TypeError: can't access dead object

26-28-2019 00:28:39 15Scends:INFO:获取物流节点信息和截图
26-28-2019 00:28:40 15Scends:INFO:已签收 2019-07-23 18:43 已签收,感谢使用顺丰,期待再次为您服务
26-28-2019 00:28:40 15Scends:INFO:运送中 2019-07-23 08:09 快件到达顺丰合作点【李莎便利店】,请携带有效证件前往自取
26-28-2019 00:28:40 15Scends:INFO:派送中 2019-07-23 07:47 快件交给郭志友，正在派送途中（联系电话：13177890792）
26-28-2019 00:28:40 15Scends:INFO:运送中 2019-07-23 07:00 快件到达 【财大速运营业点】
26-28-2019 00:28:40 15Scends:INFO:运送中 2019-07-23 06:10 快件已发车
26-28-2019 00:28:40 15Scends:INFO:运送中 2019-07-23 06:10 快件在【南昌昌北集散中心2】已装车,准备发往 【财大速运营业点】
26-28-2019 00:28:40 15Scends:INFO:运送中 2019-07-23 03:07 快件到达 【南昌昌北集散中心2】
26-28-2019 00:28:40 15Scends:INFO:运送中 2019-07-22 18:26 快件已发车
26-28-2019 00:28:40 15Scends:INFO:运送中 2019-07-22 17:56 快件在【杭州总集散中心】已装车,准备发往 【南昌昌北集散中心2】
26-28-2019 00:28:40 15Scends:INFO:运送中 2019-07-22 17:09 快件到达 【杭州总集散中心】
26-28-2019 00:28:40 15Scends:INFO:运送中 2019-07-22 16:13 快件已发车
26-28-2019 00:28:40 15Scends:INFO:运送中 2019-07-22 14:53 快件在【杭州下沙中转场】已装车,准备发往 【杭州总集散中心】
26-28-2019 00:28:40 15Scends:INFO:运送中 2019-07-22 14:26 快件到达 【杭州下沙中转场】
26-28-2019 00:28:41 15Scends:INFO:运送中 2019-07-22 13:03 快件已发车
26-28-2019 00:28:41 15Scends:INFO:运送中 2019-07-22 13:00 快件在【杭州余杭南湖丽景营业部】已装车,准备发往 【杭州余杭南湖丽景营业部】
26-28-2019 00:28:41 15Scends:INFO:已取件 2019-07-22 11:27 顺丰速运 已收取快件
26-28-2019 00:28:41 15Scends:INFO:正在获取电子存单信息和截图
26-28-2019 00:28:44 15Scends:INFO:目的地：
26-28-2019 00:28:44 15Scends:INFO:791GA
26-28-2019 00:28:44 15Scends:INFO:寄件方：杭州万源
26-28-2019 00:28:44 15Scends:INFO:杭州万源 187****9383
26-28-2019 00:28:44 15Scends:INFO:浙江省杭州市余杭区请当面验货，如外包装变形或破损请不要签收并及时与我们联系！！！
26-28-2019 00:28:44 15Scends:INFO:收件方：彭鑫威
26-28-2019 00:28:44 15Scends:INFO:彭鑫威 158****9403
26-28-2019 00:28:44 15Scends:INFO:江西省南昌市江西省南昌市经济技术开发区江西财经大学蛟桥北校区学生宿舍15栋
26-28-2019 00:28:44 15Scends:INFO:托寄物：联想原装710s-13小新air13pro总成屏幕LQ133 产品类型： 顺丰标快
26-28-2019 00:28:44 15Scends:INFO:数量：1 付款方式： 寄付月结
26-28-2019 00:28:44 15Scends:INFO:实际重量： 1.0 件数： 1.0
26-28-2019 00:28:44 15Scends:INFO:计费重量： 1.0
26-28-2019 00:28:44 15Scends:INFO:备注：
26-28-2019 00:28:44 15Scends:INFO:收件员：40044724 收件时间：2019-07-22 12:28:14
26-28-2019 00:28:44 15Scends:INFO:正在为截图添加水印
26-28-2019 00:28:46 15Scends:INFO:单号 233679804279  用时 30.854814291000366秒
26-28-2019 00:28:46 15Scends:INFO:将物流节点和电子存根信息写入csv

26-28-2019 00:28:46 15Scends:INFO:当前进度：3/18
26-28-2019 00:28:46 15Scends:INFO:正在查询的物流单号：283850627581
26-28-2019 00:28:46 15Scends:INFO:正在输入单号进行查询
26-28-2019 00:28:51 15Scends:INFO:尝试解析滑动验证码
26-28-2019 00:28:53 15Scends:INFO:解析成功，正在模拟滑动验证码・・・
26-29-2019 00:29:05 15Scends:INFO:尝试刷新验证码
26-29-2019 00:29:07 15Scends:INFO:尝试解析滑动验证码
26-29-2019 00:29:09 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 280, in get_verify_img
    img = self.browser.find_element_by_xpath('//img[@id="slideBkg"]')
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: TypeError: can't access dead object

26-29-2019 00:29:09 15Scends:INFO:解析成功，正在模拟滑动验证码・・・
26-29-2019 00:29:09 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 152, in __reload_verify_img
    self.move_slider()
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 337, in move_slider
    '//div[@id="tcaptcha_drag_button"]')
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: TypeError: can't access dead object

26-29-2019 00:29:11 15Scends:INFO:获取物流节点信息和截图
26-29-2019 00:29:13 15Scends:INFO:已签收 2019-07-16 10:43 代签收(装备室 ),感谢使用顺丰,期待再次为您服务
26-29-2019 00:29:13 15Scends:INFO:派送中 2019-07-16 08:43 快件交给高庆义，正在派送途中（联系电话：13522246802）
26-29-2019 00:29:14 15Scends:INFO:派送中 2019-07-16 08:42 快件交给耿纪友，正在派送途中（联系电话：18001028394）
26-29-2019 00:29:14 15Scends:INFO:运送中 2019-07-16 07:36 快件到达 【北京海淀科贸营业点】
26-29-2019 00:29:14 15Scends:INFO:运送中 2019-07-16 05:58 快件已发车
26-29-2019 00:29:14 15Scends:INFO:运送中 2019-07-16 02:05 快件在【北京南法信中转场】已装车,准备发往 【北京海淀科贸营业点】
26-29-2019 00:29:14 15Scends:INFO:运送中 2019-07-16 00:50 快件到达 【北京南法信中转场】
26-29-2019 00:29:14 15Scends:INFO:运送中 2019-07-16 00:44 快件已发车
26-29-2019 00:29:14 15Scends:INFO:运送中 2019-07-16 00:05 快件在【北京顺义集散中心】已装车,准备发往 【北京南法信中转场】
26-29-2019 00:29:14 15Scends:INFO:运送中 2019-07-15 23:24 快件到达 【北京顺义集散中心】
26-29-2019 00:29:14 15Scends:INFO:运送中 2019-07-15 06:06 快件已发车
26-29-2019 00:29:14 15Scends:INFO:运送中 2019-07-15 04:56 快件在【西北枢纽分拨中心】已装车,准备发往 【北京马驹桥集散中心】
26-29-2019 00:29:14 15Scends:INFO:运送中 2019-07-15 03:43 快件到达 【西北枢纽分拨中心】
26-29-2019 00:29:14 15Scends:INFO:运送中 2019-07-14 21:50 快件已发车
26-29-2019 00:29:14 15Scends:INFO:运送中 2019-07-14 20:14 快件在【天水麦积集散点】已装车,准备发往 【西北枢纽分拨中心】
26-29-2019 00:29:14 15Scends:INFO:运送中 2019-07-14 20:10 快件到达 【天水麦积集散点】
26-29-2019 00:29:14 15Scends:INFO:运送中 2019-07-14 17:41 快件已发车
26-29-2019 00:29:14 15Scends:INFO:运送中 2019-07-14 17:11 快件在【陇南市成县支旗村营业点】已装车,准备发往 【陇南市成县支旗村营业点】
26-29-2019 00:29:14 15Scends:INFO:已取件 2019-07-14 11:54 顺丰速运 已收取快件
26-29-2019 00:29:14 15Scends:INFO:正在获取电子存单信息和截图
26-29-2019 00:29:14 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 398, in get_dzcg_info
    '//div[@class="operates-wrapper"]/a').click()
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="operates-wrapper"]/a

26-29-2019 00:29:14 15Scends:INFO:该单号对应的手机号与扫码的微信号可能不符，无法获取电子存根截图
26-29-2019 00:29:14 15Scends:INFO:正在为截图添加水印
26-29-2019 00:29:14 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 422, in add_watermark
    self.__watermark(self.screenshot_img2)
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 115, in __watermark
    im = Image.open(imageFile)
  File "C:\Program Files\Python36\lib\site-packages\PIL\Image.py", line 2634, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\python_wwcheng\\sf_express\\Output\\2019-07-26 00-27-07\\img\\3-dzcg-283850627581.png'
26-29-2019 00:29:14 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 430, in next_bill_number
    '//button[@class="close"]').click()
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //button[@class="close"]

26-29-2019 00:29:15 15Scends:INFO:单号 283850627581  用时 29.08005976676941秒
26-29-2019 00:29:15 15Scends:INFO:将物流节点和电子存根信息写入csv

26-29-2019 00:29:15 15Scends:INFO:当前进度：4/18
26-29-2019 00:29:15 15Scends:INFO:正在查询的物流单号：SF1002139455289
26-29-2019 00:29:15 15Scends:INFO:正在输入单号进行查询
26-29-2019 00:29:19 15Scends:INFO:尝试解析滑动验证码
26-29-2019 00:29:20 15Scends:INFO:解析成功，正在模拟滑动验证码・・・
26-29-2019 00:29:30 15Scends:INFO:尝试刷新验证码
26-29-2019 00:29:31 15Scends:INFO:尝试解析滑动验证码
26-29-2019 00:29:32 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 280, in get_verify_img
    img = self.browser.find_element_by_xpath('//img[@id="slideBkg"]')
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: TypeError: can't access dead object

26-29-2019 00:29:32 15Scends:INFO:解析成功，正在模拟滑动验证码・・・
26-29-2019 00:29:32 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 152, in __reload_verify_img
    self.move_slider()
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 337, in move_slider
    '//div[@id="tcaptcha_drag_button"]')
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: TypeError: can't access dead object

26-29-2019 00:29:33 15Scends:INFO:获取物流节点信息和截图
26-29-2019 00:29:36 15Scends:INFO:已签收 2019-07-15 08:53 代签收(曹志平 ),感谢使用顺丰,期待再次为您服务
26-29-2019 00:29:36 15Scends:INFO:派送中 2019-07-15 08:06 快件交给蒋田波，正在派送途中（联系电话：15886508081）
26-29-2019 00:29:36 15Scends:INFO:运送中 2019-07-15 01:59 快件到达 【深圳坪山新区坪环街道营业部】
26-29-2019 00:29:36 15Scends:INFO:运送中 2019-07-15 01:02 快件已发车
26-29-2019 00:29:36 15Scends:INFO:运送中 2019-07-15 01:01 快件在【深圳五和集散中心】已装车,准备发往 【深圳坪山新区坪环街道营业部】
26-29-2019 00:29:36 15Scends:INFO:运送中 2019-07-14 18:50 快件到达 【深圳五和集散中心】
26-29-2019 00:29:36 15Scends:INFO:运送中 2019-07-14 16:40 快件已发车
26-29-2019 00:29:36 15Scends:INFO:运送中 2019-07-14 16:26 快件在【广州新塘集散中心】已装车,准备发往 【深圳五和集散中心】
26-29-2019 00:29:36 15Scends:INFO:运送中 2019-07-14 15:26 快件到达 【广州新塘集散中心】
26-29-2019 00:29:36 15Scends:INFO:运送中 2019-07-14 14:25 快件已发车
26-29-2019 00:29:36 15Scends:INFO:运送中 2019-07-14 14:15 快件在【广州白云萧岗明珠北路营业部】已装车,准备发往 【广州新塘集散中心】
26-29-2019 00:29:36 15Scends:INFO:已取件 2019-07-14 11:15 顺丰速运 已收取快件
26-29-2019 00:29:36 15Scends:INFO:正在获取电子存单信息和截图
26-29-2019 00:29:36 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 398, in get_dzcg_info
    '//div[@class="operates-wrapper"]/a').click()
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="operates-wrapper"]/a

26-29-2019 00:29:36 15Scends:INFO:该单号对应的手机号与扫码的微信号可能不符，无法获取电子存根截图
26-29-2019 00:29:36 15Scends:INFO:正在为截图添加水印
26-29-2019 00:29:36 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 422, in add_watermark
    self.__watermark(self.screenshot_img2)
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 115, in __watermark
    im = Image.open(imageFile)
  File "C:\Program Files\Python36\lib\site-packages\PIL\Image.py", line 2634, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\python_wwcheng\\sf_express\\Output\\2019-07-26 00-27-07\\img\\4-dzcg-SF1002139455289.png'
26-29-2019 00:29:36 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 430, in next_bill_number
    '//button[@class="close"]').click()
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //button[@class="close"]

26-29-2019 00:29:37 15Scends:INFO:单号 SF1002139455289  用时 21.47919011116028秒
26-29-2019 00:29:37 15Scends:INFO:将物流节点和电子存根信息写入csv

26-29-2019 00:29:37 15Scends:INFO:当前进度：5/18
26-29-2019 00:29:37 15Scends:INFO:正在查询的物流单号：233441276116
26-29-2019 00:29:37 15Scends:INFO:正在输入单号进行查询
26-29-2019 00:29:42 15Scends:INFO:尝试解析滑动验证码
26-29-2019 00:29:43 15Scends:INFO:解析成功，正在模拟滑动验证码・・・
26-29-2019 00:29:56 15Scends:INFO:尝试刷新验证码
26-29-2019 00:29:58 15Scends:INFO:尝试解析滑动验证码
26-30-2019 00:30:00 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 280, in get_verify_img
    img = self.browser.find_element_by_xpath('//img[@id="slideBkg"]')
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: TypeError: can't access dead object

26-30-2019 00:30:00 15Scends:INFO:解析成功，正在模拟滑动验证码・・・
26-30-2019 00:30:00 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 152, in __reload_verify_img
    self.move_slider()
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 337, in move_slider
    '//div[@id="tcaptcha_drag_button"]')
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: TypeError: can't access dead object

26-30-2019 00:30:02 15Scends:INFO:获取物流节点信息和截图
26-30-2019 00:30:04 15Scends:INFO:运送中 2019-07-16 14:13 [两河口支局]在 汉中市 已签收,本人签收 :王佳宇,投递员:张军:18329661822
26-30-2019 00:30:04 15Scends:INFO:运送中 2019-07-15 15:57 【两河口支局】投递结果反馈-未妥投,备注(其他 ),投递员:张军:18329661822
26-30-2019 00:30:04 15Scends:INFO:运送中 2019-07-15 10:32 到达【两河口支局】
26-30-2019 00:30:04 15Scends:INFO:运送中 2019-07-15 08:35 【两河口支局】安排投递,投递员:张军:18329661822
26-30-2019 00:30:04 15Scends:INFO:运送中 2019-07-13 12:52 离开【略阳寄递】,下一站【两河口支局】
26-30-2019 00:30:04 15Scends:INFO:运送中 2019-07-13 12:30 到达【略阳寄递】
26-30-2019 00:30:05 15Scends:INFO:运送中 2019-07-13 12:03 离开【中国邮政集团公司汉中市略阳县寄递事业部】,下一站【略阳处理】
26-30-2019 00:30:05 15Scends:INFO:运送中 2019-07-13 09:01 汉中市 【中国邮政集团公司汉中市略阳县寄递事业部】已收件,揽投员:高丽霞13008462300
26-30-2019 00:30:05 15Scends:INFO:运送中 2019-07-12 11:33 快件转寄【EMS】, 单号【9661052919944】,转寄的寄递信息为第三方信息方提供
26-30-2019 00:30:05 15Scends:INFO:运送中 2019-07-12 11:33 快件已转寄
26-30-2019 00:30:05 15Scends:INFO:派送中 2019-07-12 08:00 快件派送不成功（因无法满足客户派件需求），待进一步处理
26-30-2019 00:30:05 15Scends:INFO:运送中 2019-07-12 07:54 快件到达 【汉中略阳陈家沟速运营业点】
26-30-2019 00:30:05 15Scends:INFO:运送中 2019-07-12 05:56 快件已发车
26-30-2019 00:30:05 15Scends:INFO:运送中 2019-07-12 05:56 快件在【汉中汉台集散点】已装车,准备发往 【汉中略阳陈家沟速运营业点】
26-30-2019 00:30:05 15Scends:INFO:运送中 2019-07-12 04:15 快件到达 【汉中汉台集散点】
26-30-2019 00:30:05 15Scends:INFO:运送中 2019-07-11 23:23 快件已发车
26-30-2019 00:30:05 15Scends:INFO:运送中 2019-07-11 21:22 快件在【西安总集散中心】已装车,准备发往 【汉中汉台集散点】
26-30-2019 00:30:05 15Scends:INFO:运送中 2019-07-11 14:21 快件到达 【西安总集散中心】
26-30-2019 00:30:05 15Scends:INFO:落地 2019-07-11 12:47 快件到达【西安】，准备发往【西安总集散中心】
26-30-2019 00:30:05 15Scends:INFO:起飞 2019-07-11 07:16 快件在【厦门飞往西安航班上】已起飞
26-30-2019 00:30:05 15Scends:INFO:运送中 2019-07-11 01:57 快件在【厦门总集散中心】已装车,准备发往 【西安总集散中心】
26-30-2019 00:30:05 15Scends:INFO:运送中 2019-07-11 01:24 快件到达 【厦门总集散中心】
26-30-2019 00:30:05 15Scends:INFO:运送中 2019-07-11 00:12 快件已发车
26-30-2019 00:30:05 15Scends:INFO:运送中 2019-07-10 19:58 快件在【泉州晋江集散中心】已装车,准备发往 【厦门总集散中心】
26-30-2019 00:30:05 15Scends:INFO:运送中 2019-07-10 18:57 快件到达 【泉州晋江集散中心】
26-30-2019 00:30:05 15Scends:INFO:运送中 2019-07-10 17:32 快件已发车
26-30-2019 00:30:05 15Scends:INFO:运送中 2019-07-10 15:33 快件在【泉州市大客户项目营业部】已装车,准备发往 【晋江西滨跃进路营业点】
26-30-2019 00:30:05 15Scends:INFO:已揽收 2019-07-10 15:28 顺丰速运 已收取快件
26-30-2019 00:30:05 15Scends:INFO:正在获取电子存单信息和截图
26-30-2019 00:30:05 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 398, in get_dzcg_info
    '//div[@class="operates-wrapper"]/a').click()
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="operates-wrapper"]/a

26-30-2019 00:30:05 15Scends:INFO:该单号对应的手机号与扫码的微信号可能不符，无法获取电子存根截图
26-30-2019 00:30:05 15Scends:INFO:正在为截图添加水印
26-30-2019 00:30:05 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 422, in add_watermark
    self.__watermark(self.screenshot_img2)
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 115, in __watermark
    im = Image.open(imageFile)
  File "C:\Program Files\Python36\lib\site-packages\PIL\Image.py", line 2634, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\python_wwcheng\\sf_express\\Output\\2019-07-26 00-27-07\\img\\5-dzcg-233441276116.png'
26-30-2019 00:30:05 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 430, in next_bill_number
    '//button[@class="close"]').click()
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //button[@class="close"]

26-30-2019 00:30:06 15Scends:INFO:单号 233441276116  用时 29.51843285560608秒
26-30-2019 00:30:06 15Scends:INFO:将物流节点和电子存根信息写入csv

26-30-2019 00:30:07 15Scends:INFO:当前进度：6/18
26-30-2019 00:30:07 15Scends:INFO:正在查询的物流单号：747193990676
26-30-2019 00:30:07 15Scends:INFO:正在输入单号进行查询
26-30-2019 00:30:12 15Scends:INFO:尝试解析滑动验证码
26-30-2019 00:30:14 15Scends:INFO:解析成功，正在模拟滑动验证码・・・
26-30-2019 00:30:26 15Scends:INFO:尝试刷新验证码
26-30-2019 00:30:27 15Scends:INFO:尝试解析滑动验证码
26-30-2019 00:30:28 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 280, in get_verify_img
    img = self.browser.find_element_by_xpath('//img[@id="slideBkg"]')
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: TypeError: can't access dead object

26-30-2019 00:30:29 15Scends:INFO:解析成功，正在模拟滑动验证码・・・
26-30-2019 00:30:29 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 152, in __reload_verify_img
    self.move_slider()
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 337, in move_slider
    '//div[@id="tcaptcha_drag_button"]')
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: TypeError: can't access dead object

26-30-2019 00:30:30 15Scends:INFO:获取物流节点信息和截图
26-30-2019 00:30:31 15Scends:INFO:已签收 2019-07-25 18:11 已签收,感谢使用顺丰,期待再次为您服务
26-30-2019 00:30:31 15Scends:INFO:派送中 2019-07-25 17:50 快件交给张德，正在派送途中（联系电话：15056886382）
26-30-2019 00:30:31 15Scends:INFO:派送中 2019-07-25 16:48 快件交给李永杰，正在派送途中（联系电话：18383915871）
26-30-2019 00:30:31 15Scends:INFO:运送中 2019-07-25 16:27 快件到达 【苏州工业园东环路营业点】
26-30-2019 00:30:31 15Scends:INFO:运送中 2019-07-25 15:42 快件已发车
26-30-2019 00:30:31 15Scends:INFO:运送中 2019-07-25 14:56 快件在【苏州吴中集散中心】已装车,准备发往 【苏州工业园东环路营业点】
26-30-2019 00:30:31 15Scends:INFO:运送中 2019-07-25 13:58 快件到达 【苏州吴中集散中心】
26-30-2019 00:30:31 15Scends:INFO:运送中 2019-07-25 07:26 快件已发车
26-30-2019 00:30:31 15Scends:INFO:运送中 2019-07-25 04:52 快件在【连云港海州集散中心】已装车,准备发往 【苏州吴中集散中心】
26-30-2019 00:30:31 15Scends:INFO:运送中 2019-07-25 04:27 快件到达 【连云港海州集散中心】
26-30-2019 00:30:31 15Scends:INFO:运送中 2019-07-24 22:49 快件已发车
26-30-2019 00:30:31 15Scends:INFO:运送中 2019-07-24 22:15 快件在【滨州天工集散点】已装车,准备发往 【连云港海州集散中心】
26-30-2019 00:30:31 15Scends:INFO:运送中 2019-07-24 20:46 快件到达 【滨州天工集散点】
26-30-2019 00:30:31 15Scends:INFO:运送中 2019-07-24 19:13 快件已发车
26-30-2019 00:30:32 15Scends:INFO:运送中 2019-07-24 19:09 快件在【东营市河口区河庆路营业点】已装车,准备发往 【滨州天工集散点】
26-30-2019 00:30:32 15Scends:INFO:已取件 2019-07-24 15:23 顺丰速运 已收取快件
26-30-2019 00:30:32 15Scends:INFO:正在获取电子存单信息和截图
26-30-2019 00:30:32 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 398, in get_dzcg_info
    '//div[@class="operates-wrapper"]/a').click()
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="operates-wrapper"]/a

26-30-2019 00:30:32 15Scends:INFO:该单号对应的手机号与扫码的微信号可能不符，无法获取电子存根截图
26-30-2019 00:30:32 15Scends:INFO:正在为截图添加水印
26-30-2019 00:30:32 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 422, in add_watermark
    self.__watermark(self.screenshot_img2)
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 115, in __watermark
    im = Image.open(imageFile)
  File "C:\Program Files\Python36\lib\site-packages\PIL\Image.py", line 2634, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\python_wwcheng\\sf_express\\Output\\2019-07-26 00-27-07\\img\\6-dzcg-747193990676.png'
26-30-2019 00:30:32 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 430, in next_bill_number
    '//button[@class="close"]').click()
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //button[@class="close"]

26-30-2019 00:30:33 15Scends:INFO:单号 747193990676  用时 26.221431732177734秒
26-30-2019 00:30:33 15Scends:INFO:将物流节点和电子存根信息写入csv

26-30-2019 00:30:33 15Scends:INFO:当前进度：7/18
26-30-2019 00:30:33 15Scends:INFO:正在查询的物流单号：283850627581
26-30-2019 00:30:33 15Scends:INFO:正在输入单号进行查询
26-30-2019 00:30:36 15Scends:INFO:尝试解析滑动验证码
26-30-2019 00:30:38 15Scends:INFO:解析成功，正在模拟滑动验证码・・・
26-30-2019 00:30:50 15Scends:INFO:尝试刷新验证码
26-30-2019 00:30:52 15Scends:INFO:尝试解析滑动验证码
26-30-2019 00:30:54 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 280, in get_verify_img
    img = self.browser.find_element_by_xpath('//img[@id="slideBkg"]')
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: TypeError: can't access dead object

26-30-2019 00:30:54 15Scends:INFO:解析成功，正在模拟滑动验证码・・・
26-30-2019 00:30:54 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 152, in __reload_verify_img
    self.move_slider()
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 337, in move_slider
    '//div[@id="tcaptcha_drag_button"]')
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: TypeError: can't access dead object

26-30-2019 00:30:56 15Scends:INFO:获取物流节点信息和截图
26-30-2019 00:30:59 15Scends:INFO:已签收 2019-07-16 10:43 代签收(装备室 ),感谢使用顺丰,期待再次为您服务
26-30-2019 00:30:59 15Scends:INFO:派送中 2019-07-16 08:43 快件交给高庆义，正在派送途中（联系电话：13522246802）
26-30-2019 00:30:59 15Scends:INFO:派送中 2019-07-16 08:42 快件交给耿纪友，正在派送途中（联系电话：18001028394）
26-30-2019 00:30:59 15Scends:INFO:运送中 2019-07-16 07:36 快件到达 【北京海淀科贸营业点】
26-30-2019 00:30:59 15Scends:INFO:运送中 2019-07-16 05:58 快件已发车
26-30-2019 00:30:59 15Scends:INFO:运送中 2019-07-16 02:05 快件在【北京南法信中转场】已装车,准备发往 【北京海淀科贸营业点】
26-30-2019 00:30:59 15Scends:INFO:运送中 2019-07-16 00:50 快件到达 【北京南法信中转场】
26-30-2019 00:30:59 15Scends:INFO:运送中 2019-07-16 00:44 快件已发车
26-30-2019 00:30:59 15Scends:INFO:运送中 2019-07-16 00:05 快件在【北京顺义集散中心】已装车,准备发往 【北京南法信中转场】
26-30-2019 00:30:59 15Scends:INFO:运送中 2019-07-15 23:24 快件到达 【北京顺义集散中心】
26-30-2019 00:30:59 15Scends:INFO:运送中 2019-07-15 06:06 快件已发车
26-30-2019 00:30:59 15Scends:INFO:运送中 2019-07-15 04:56 快件在【西北枢纽分拨中心】已装车,准备发往 【北京马驹桥集散中心】
26-30-2019 00:30:59 15Scends:INFO:运送中 2019-07-15 03:43 快件到达 【西北枢纽分拨中心】
26-30-2019 00:30:59 15Scends:INFO:运送中 2019-07-14 21:50 快件已发车
26-30-2019 00:30:59 15Scends:INFO:运送中 2019-07-14 20:14 快件在【天水麦积集散点】已装车,准备发往 【西北枢纽分拨中心】
26-30-2019 00:30:59 15Scends:INFO:运送中 2019-07-14 20:10 快件到达 【天水麦积集散点】
26-30-2019 00:30:59 15Scends:INFO:运送中 2019-07-14 17:41 快件已发车
26-30-2019 00:30:59 15Scends:INFO:运送中 2019-07-14 17:11 快件在【陇南市成县支旗村营业点】已装车,准备发往 【陇南市成县支旗村营业点】
26-30-2019 00:30:59 15Scends:INFO:已取件 2019-07-14 11:54 顺丰速运 已收取快件
26-30-2019 00:30:59 15Scends:INFO:正在获取电子存单信息和截图
26-30-2019 00:30:59 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 398, in get_dzcg_info
    '//div[@class="operates-wrapper"]/a').click()
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="operates-wrapper"]/a

26-30-2019 00:30:59 15Scends:INFO:该单号对应的手机号与扫码的微信号可能不符，无法获取电子存根截图
26-30-2019 00:30:59 15Scends:INFO:正在为截图添加水印
26-30-2019 00:30:59 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 422, in add_watermark
    self.__watermark(self.screenshot_img2)
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 115, in __watermark
    im = Image.open(imageFile)
  File "C:\Program Files\Python36\lib\site-packages\PIL\Image.py", line 2634, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\python_wwcheng\\sf_express\\Output\\2019-07-26 00-27-07\\img\\7-dzcg-283850627581.png'
26-30-2019 00:30:59 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 430, in next_bill_number
    '//button[@class="close"]').click()
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //button[@class="close"]

26-31-2019 00:31:01 15Scends:INFO:单号 283850627581  用时 28.211098670959473秒
26-31-2019 00:31:01 15Scends:INFO:将物流节点和电子存根信息写入csv

26-31-2019 00:31:01 15Scends:INFO:当前进度：8/18
26-31-2019 00:31:01 15Scends:INFO:正在查询的物流单号：365550496421
26-31-2019 00:31:01 15Scends:INFO:正在输入单号进行查询
26-31-2019 00:31:05 15Scends:INFO:尝试解析滑动验证码
26-31-2019 00:31:08 15Scends:INFO:解析成功，正在模拟滑动验证码・・・
26-31-2019 00:31:17 15Scends:INFO:尝试刷新验证码
26-31-2019 00:31:18 15Scends:INFO:尝试解析滑动验证码
26-31-2019 00:31:19 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 280, in get_verify_img
    img = self.browser.find_element_by_xpath('//img[@id="slideBkg"]')
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: TypeError: can't access dead object

26-31-2019 00:31:19 15Scends:INFO:解析成功，正在模拟滑动验证码・・・
26-31-2019 00:31:19 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 152, in __reload_verify_img
    self.move_slider()
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 337, in move_slider
    '//div[@id="tcaptcha_drag_button"]')
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: TypeError: can't access dead object

26-31-2019 00:31:20 15Scends:INFO:获取物流节点信息和截图
26-31-2019 00:31:22 15Scends:INFO:已签收 2019-07-18 18:54 已签收,感谢使用顺丰,期待再次为您服务
26-31-2019 00:31:22 15Scends:INFO:派送中 2019-07-18 15:49 快件交给刘洪国，正在派送途中（联系电话：18690270984）
26-31-2019 00:31:22 15Scends:INFO:运送中 2019-07-18 15:20 快件到达 【新疆阿克苏地区红桥速运营业点】
26-31-2019 00:31:22 15Scends:INFO:运送中 2019-07-18 15:00 快件已发车
26-31-2019 00:31:22 15Scends:INFO:运送中 2019-07-18 14:48 快件在【阿克苏集散点】已装车,准备发往 【新疆阿克苏地区红桥速运营业点】
26-31-2019 00:31:22 15Scends:INFO:运送中 2019-07-18 12:54 快件到达 【阿克苏集散点】
26-31-2019 00:31:22 15Scends:INFO:运送中 2019-07-17 16:13 快件已发车
26-31-2019 00:31:22 15Scends:INFO:运送中 2019-07-17 10:58 快件在【乌鲁木齐总集散中心】已装车,准备发往 【阿克苏集散点】
26-31-2019 00:31:22 15Scends:INFO:运送中 2019-07-17 10:32 快件到达 【乌鲁木齐总集散中心】
26-31-2019 00:31:22 15Scends:INFO:运送中 2019-07-15 05:26 快件已发车
26-31-2019 00:31:22 15Scends:INFO:运送中 2019-07-15 02:56 快件在【潍坊坊子新区集散中心】已装车,准备发往 【乌鲁木齐总集散中心】
26-31-2019 00:31:22 15Scends:INFO:运送中 2019-07-15 01:14 快件到达 【潍坊坊子新区集散中心】
26-31-2019 00:31:22 15Scends:INFO:运送中 2019-07-14 22:49 快件已发车
26-31-2019 00:31:22 15Scends:INFO:运送中 2019-07-14 22:49 快件在【烟台莱阳集散中心】已装车,准备发往 【潍坊坊子新区集散中心】
26-31-2019 00:31:22 15Scends:INFO:运送中 2019-07-14 21:11 快件到达 【烟台莱阳集散中心】
26-31-2019 00:31:22 15Scends:INFO:运送中 2019-07-14 19:31 快件已发车
26-31-2019 00:31:22 15Scends:INFO:运送中 2019-07-14 19:30 快件在【烟台莱州城港南路营业点】已装车,准备发往 【烟台莱阳集散中心】
26-31-2019 00:31:23 15Scends:INFO:已取件 2019-07-14 18:35 顺丰速运 已收取快件
26-31-2019 00:31:23 15Scends:INFO:正在获取电子存单信息和截图
26-31-2019 00:31:23 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 398, in get_dzcg_info
    '//div[@class="operates-wrapper"]/a').click()
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="operates-wrapper"]/a

26-31-2019 00:31:23 15Scends:INFO:该单号对应的手机号与扫码的微信号可能不符，无法获取电子存根截图
26-31-2019 00:31:23 15Scends:INFO:正在为截图添加水印
26-31-2019 00:31:23 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 422, in add_watermark
    self.__watermark(self.screenshot_img2)
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 115, in __watermark
    im = Image.open(imageFile)
  File "C:\Program Files\Python36\lib\site-packages\PIL\Image.py", line 2634, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\python_wwcheng\\sf_express\\Output\\2019-07-26 00-27-07\\img\\8-dzcg-365550496421.png'
26-31-2019 00:31:23 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 430, in next_bill_number
    '//button[@class="close"]').click()
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //button[@class="close"]

26-31-2019 00:31:24 15Scends:INFO:单号 365550496421  用时 22.918585538864136秒
26-31-2019 00:31:24 15Scends:INFO:将物流节点和电子存根信息写入csv

26-31-2019 00:31:24 15Scends:INFO:当前进度：9/18
26-31-2019 00:31:24 15Scends:INFO:正在查询的物流单号：368657929782
26-31-2019 00:31:24 15Scends:INFO:正在输入单号进行查询
26-31-2019 00:31:28 15Scends:INFO:尝试解析滑动验证码
26-31-2019 00:31:30 15Scends:INFO:解析成功，正在模拟滑动验证码・・・
26-31-2019 00:31:42 15Scends:INFO:尝试刷新验证码
26-31-2019 00:31:43 15Scends:INFO:尝试解析滑动验证码
26-31-2019 00:31:44 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 280, in get_verify_img
    img = self.browser.find_element_by_xpath('//img[@id="slideBkg"]')
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: TypeError: can't access dead object

26-31-2019 00:31:44 15Scends:INFO:解析成功，正在模拟滑动验证码・・・
26-31-2019 00:31:44 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 152, in __reload_verify_img
    self.move_slider()
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 337, in move_slider
    '//div[@id="tcaptcha_drag_button"]')
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: TypeError: can't access dead object

26-31-2019 00:31:46 15Scends:INFO:获取物流节点信息和截图
26-31-2019 00:31:47 15Scends:INFO:已签收 2019-07-14 18:09 已签收,感谢使用顺丰,期待再次为您服务
26-31-2019 00:31:48 15Scends:INFO:派送中 2019-07-14 17:28 快件交给王超，正在派送途中（联系电话：13699177849）
26-31-2019 00:31:48 15Scends:INFO:运送中 2019-07-14 16:34 快件到达 【庞各庄速运营业点】
26-31-2019 00:31:48 15Scends:INFO:运送中 2019-07-14 14:38 快件已发车
26-31-2019 00:31:48 15Scends:INFO:运送中 2019-07-14 14:07 快件在【北京顺义集散中心】已装车,准备发往 【庞各庄速运营业点】
26-31-2019 00:31:48 15Scends:INFO:运送中 2019-07-14 11:59 快件到达 【北京顺义集散中心】
26-31-2019 00:31:48 15Scends:INFO:运送中 2019-07-14 11:44 快件已发车
26-31-2019 00:31:48 15Scends:INFO:运送中 2019-07-14 11:39 快件在【北京国航集散中心】已装车,准备发往 【北京顺义集散中心】
26-31-2019 00:31:48 15Scends:INFO:运送中 2019-07-14 11:39 快件到达 【北京国航集散中心】
26-31-2019 00:31:48 15Scends:INFO:落地 2019-07-14 09:52 快件到达【北京】，准备发往【北京国航集散中心】
26-31-2019 00:31:48 15Scends:INFO:起飞 2019-07-14 07:45 快件在【长沙飞往北京航班上】已起飞
26-31-2019 00:31:48 15Scends:INFO:运送中 2019-07-14 01:34 快件在【长沙星沙集散中心】已装车,准备发往 【北京国航集散中心】
26-31-2019 00:31:48 15Scends:INFO:已取件 2019-07-13 15:46 顺丰速运 已收取快件
26-31-2019 00:31:48 15Scends:INFO:正在获取电子存单信息和截图
26-31-2019 00:31:48 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 398, in get_dzcg_info
    '//div[@class="operates-wrapper"]/a').click()
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="operates-wrapper"]/a

26-31-2019 00:31:48 15Scends:INFO:该单号对应的手机号与扫码的微信号可能不符，无法获取电子存根截图
26-31-2019 00:31:48 15Scends:INFO:正在为截图添加水印
26-31-2019 00:31:48 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 422, in add_watermark
    self.__watermark(self.screenshot_img2)
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 115, in __watermark
    im = Image.open(imageFile)
  File "C:\Program Files\Python36\lib\site-packages\PIL\Image.py", line 2634, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\python_wwcheng\\sf_express\\Output\\2019-07-26 00-27-07\\img\\9-dzcg-368657929782.png'
26-31-2019 00:31:48 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 430, in next_bill_number
    '//button[@class="close"]').click()
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //button[@class="close"]

26-31-2019 00:31:49 15Scends:INFO:单号 368657929782  用时 24.89770817756653秒
26-31-2019 00:31:49 15Scends:INFO:将物流节点和电子存根信息写入csv

26-31-2019 00:31:49 15Scends:INFO:当前进度：10/18
26-31-2019 00:31:49 15Scends:INFO:正在查询的物流单号：283850627581
26-31-2019 00:31:49 15Scends:INFO:正在输入单号进行查询
26-31-2019 00:31:53 15Scends:INFO:尝试解析滑动验证码
26-31-2019 00:31:55 15Scends:INFO:解析成功，正在模拟滑动验证码・・・
26-32-2019 00:32:04 15Scends:INFO:尝试刷新验证码
26-32-2019 00:32:06 15Scends:INFO:尝试解析滑动验证码
26-32-2019 00:32:07 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 280, in get_verify_img
    img = self.browser.find_element_by_xpath('//img[@id="slideBkg"]')
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: TypeError: can't access dead object

26-32-2019 00:32:07 15Scends:INFO:解析成功，正在模拟滑动验证码・・・
26-32-2019 00:32:07 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 152, in __reload_verify_img
    self.move_slider()
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 337, in move_slider
    '//div[@id="tcaptcha_drag_button"]')
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: TypeError: can't access dead object

26-32-2019 00:32:09 15Scends:INFO:获取物流节点信息和截图
26-32-2019 00:32:12 15Scends:INFO:已签收 2019-07-16 10:43 代签收(装备室 ),感谢使用顺丰,期待再次为您服务
26-32-2019 00:32:12 15Scends:INFO:派送中 2019-07-16 08:43 快件交给高庆义，正在派送途中（联系电话：13522246802）
26-32-2019 00:32:12 15Scends:INFO:派送中 2019-07-16 08:42 快件交给耿纪友，正在派送途中（联系电话：18001028394）
26-32-2019 00:32:12 15Scends:INFO:运送中 2019-07-16 07:36 快件到达 【北京海淀科贸营业点】
26-32-2019 00:32:12 15Scends:INFO:运送中 2019-07-16 05:58 快件已发车
26-32-2019 00:32:12 15Scends:INFO:运送中 2019-07-16 02:05 快件在【北京南法信中转场】已装车,准备发往 【北京海淀科贸营业点】
26-32-2019 00:32:12 15Scends:INFO:运送中 2019-07-16 00:50 快件到达 【北京南法信中转场】
26-32-2019 00:32:12 15Scends:INFO:运送中 2019-07-16 00:44 快件已发车
26-32-2019 00:32:12 15Scends:INFO:运送中 2019-07-16 00:05 快件在【北京顺义集散中心】已装车,准备发往 【北京南法信中转场】
26-32-2019 00:32:12 15Scends:INFO:运送中 2019-07-15 23:24 快件到达 【北京顺义集散中心】
26-32-2019 00:32:12 15Scends:INFO:运送中 2019-07-15 06:06 快件已发车
26-32-2019 00:32:12 15Scends:INFO:运送中 2019-07-15 04:56 快件在【西北枢纽分拨中心】已装车,准备发往 【北京马驹桥集散中心】
26-32-2019 00:32:12 15Scends:INFO:运送中 2019-07-15 03:43 快件到达 【西北枢纽分拨中心】
26-32-2019 00:32:12 15Scends:INFO:运送中 2019-07-14 21:50 快件已发车
26-32-2019 00:32:12 15Scends:INFO:运送中 2019-07-14 20:14 快件在【天水麦积集散点】已装车,准备发往 【西北枢纽分拨中心】
26-32-2019 00:32:12 15Scends:INFO:运送中 2019-07-14 20:10 快件到达 【天水麦积集散点】
26-32-2019 00:32:12 15Scends:INFO:运送中 2019-07-14 17:41 快件已发车
26-32-2019 00:32:12 15Scends:INFO:运送中 2019-07-14 17:11 快件在【陇南市成县支旗村营业点】已装车,准备发往 【陇南市成县支旗村营业点】
26-32-2019 00:32:12 15Scends:INFO:已取件 2019-07-14 11:54 顺丰速运 已收取快件
26-32-2019 00:32:12 15Scends:INFO:正在获取电子存单信息和截图
26-32-2019 00:32:12 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 398, in get_dzcg_info
    '//div[@class="operates-wrapper"]/a').click()
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="operates-wrapper"]/a

26-32-2019 00:32:12 15Scends:INFO:该单号对应的手机号与扫码的微信号可能不符，无法获取电子存根截图
26-32-2019 00:32:12 15Scends:INFO:正在为截图添加水印
26-32-2019 00:32:12 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 422, in add_watermark
    self.__watermark(self.screenshot_img2)
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 115, in __watermark
    im = Image.open(imageFile)
  File "C:\Program Files\Python36\lib\site-packages\PIL\Image.py", line 2634, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\python_wwcheng\\sf_express\\Output\\2019-07-26 00-27-07\\img\\10-dzcg-283850627581.png'
26-32-2019 00:32:12 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 430, in next_bill_number
    '//button[@class="close"]').click()
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //button[@class="close"]

26-32-2019 00:32:14 15Scends:INFO:单号 283850627581  用时 25.356444120407104秒
26-32-2019 00:32:14 15Scends:INFO:将物流节点和电子存根信息写入csv

26-32-2019 00:32:14 15Scends:INFO:当前进度：11/18
26-32-2019 00:32:14 15Scends:INFO:正在查询的物流单号：349342485986
26-32-2019 00:32:14 15Scends:INFO:正在输入单号进行查询
26-32-2019 00:32:18 15Scends:INFO:尝试解析滑动验证码
26-32-2019 00:32:20 15Scends:INFO:解析成功，正在模拟滑动验证码・・・
26-32-2019 00:32:30 15Scends:INFO:尝试刷新验证码
26-32-2019 00:32:33 15Scends:INFO:尝试解析滑动验证码
26-32-2019 00:32:33 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 280, in get_verify_img
    img = self.browser.find_element_by_xpath('//img[@id="slideBkg"]')
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: TypeError: can't access dead object

26-32-2019 00:32:33 15Scends:INFO:解析成功，正在模拟滑动验证码・・・
26-32-2019 00:32:33 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 152, in __reload_verify_img
    self.move_slider()
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 337, in move_slider
    '//div[@id="tcaptcha_drag_button"]')
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: TypeError: can't access dead object

26-32-2019 00:32:34 15Scends:INFO:获取物流节点信息和截图
26-32-2019 00:32:36 15Scends:INFO:已签收 2019-07-15 11:20 已签收,感谢使用顺丰,期待再次为您服务
26-32-2019 00:32:36 15Scends:INFO:派送中 2019-07-15 11:18 快件交给尤川，正在派送途中（联系电话：13312638018）
26-32-2019 00:32:36 15Scends:INFO:派送中 2019-07-15 11:17 正在派送途中,请您准备签收(派件人:尤川,电话:13312638018)
26-32-2019 00:32:36 15Scends:INFO:派送中 2019-07-15 10:44 收方客户要求自取快件,待自取
26-32-2019 00:32:36 15Scends:INFO:运送中 2019-07-15 10:43 收方客户要求自取快件,待自取
26-32-2019 00:32:37 15Scends:INFO:派送中 2019-07-15 07:53 快件交给尤川，正在派送途中（联系电话：13312638018）
26-32-2019 00:32:37 15Scends:INFO:运送中 2019-07-15 07:12 快件到达 【曲靖麒麟瑞和新城营业点】
26-32-2019 00:32:37 15Scends:INFO:运送中 2019-07-15 06:47 快件已发车
26-32-2019 00:32:37 15Scends:INFO:运送中 2019-07-15 05:09 快件在【曲靖麒麟集散点】已装车,准备发往 【曲靖麒麟瑞和新城营业点】
26-32-2019 00:32:37 15Scends:INFO:运送中 2019-07-14 23:27 快件到达 【曲靖麒麟集散点】
26-32-2019 00:32:37 15Scends:INFO:运送中 2019-07-14 19:57 快件已发车
26-32-2019 00:32:37 15Scends:INFO:运送中 2019-07-14 19:56 快件在【昆明王家营集散中心】已装车,准备发往 【昆明临时中转场】
26-32-2019 00:32:37 15Scends:INFO:运送中 2019-07-14 19:00 快件到达 【昆明王家营集散中心】
26-32-2019 00:32:37 15Scends:INFO:运送中 2019-07-14 17:54 快件已发车
26-32-2019 00:32:37 15Scends:INFO:运送中 2019-07-14 17:20 快件在【昆明盘龙新迎小区营业点】已装车,准备发往 【昆明市盘龙区灵光街营业点】
26-32-2019 00:32:37 15Scends:INFO:已取件 2019-07-14 14:40 顺丰速运 已收取快件
26-32-2019 00:32:37 15Scends:INFO:正在获取电子存单信息和截图
26-32-2019 00:32:37 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 398, in get_dzcg_info
    '//div[@class="operates-wrapper"]/a').click()
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="operates-wrapper"]/a

26-32-2019 00:32:37 15Scends:INFO:该单号对应的手机号与扫码的微信号可能不符，无法获取电子存根截图
26-32-2019 00:32:37 15Scends:INFO:正在为截图添加水印
26-32-2019 00:32:37 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 422, in add_watermark
    self.__watermark(self.screenshot_img2)
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 115, in __watermark
    im = Image.open(imageFile)
  File "C:\Program Files\Python36\lib\site-packages\PIL\Image.py", line 2634, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\python_wwcheng\\sf_express\\Output\\2019-07-26 00-27-07\\img\\11-dzcg-349342485986.png'
26-32-2019 00:32:37 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 430, in next_bill_number
    '//button[@class="close"]').click()
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //button[@class="close"]

26-32-2019 00:32:39 15Scends:INFO:单号 349342485986  用时 24.813692331314087秒
26-32-2019 00:32:39 15Scends:INFO:将物流节点和电子存根信息写入csv

26-32-2019 00:32:39 15Scends:INFO:当前进度：12/18
26-32-2019 00:32:39 15Scends:INFO:正在查询的物流单号：349247356730
26-32-2019 00:32:39 15Scends:INFO:正在输入单号进行查询
26-32-2019 00:32:44 15Scends:INFO:尝试解析滑动验证码
26-32-2019 00:32:45 15Scends:INFO:解析成功，正在模拟滑动验证码・・・
26-32-2019 00:32:56 15Scends:INFO:尝试刷新验证码
26-32-2019 00:32:58 15Scends:INFO:尝试解析滑动验证码
26-32-2019 00:32:59 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 280, in get_verify_img
    img = self.browser.find_element_by_xpath('//img[@id="slideBkg"]')
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: TypeError: can't access dead object

26-33-2019 00:33:00 15Scends:INFO:解析成功，正在模拟滑动验证码・・・
26-33-2019 00:33:00 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 152, in __reload_verify_img
    self.move_slider()
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 337, in move_slider
    '//div[@id="tcaptcha_drag_button"]')
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: TypeError: can't access dead object

26-33-2019 00:33:01 15Scends:INFO:获取物流节点信息和截图
26-33-2019 00:33:03 15Scends:INFO:已签收 2019-07-15 10:47 已签收,感谢使用顺丰,期待再次为您服务
26-33-2019 00:33:03 15Scends:INFO:派送中 2019-07-15 09:42 快件交给杨建军，正在派送途中（联系电话：18199175636）
26-33-2019 00:33:03 15Scends:INFO:运送中 2019-07-15 09:04 快件到达 【新疆乌市成功速运营业点】
26-33-2019 00:33:03 15Scends:INFO:运送中 2019-07-15 07:51 快件已发车
26-33-2019 00:33:03 15Scends:INFO:运送中 2019-07-15 07:05 快件在【乌鲁木齐集散中心】已装车,准备发往 【新疆乌市成功速运营业点】
26-33-2019 00:33:03 15Scends:INFO:运送中 2019-07-15 01:05 快件到达 【乌鲁木齐集散中心】
26-33-2019 00:33:03 15Scends:INFO:运送中 2019-07-15 00:25 快件已发车
26-33-2019 00:33:03 15Scends:INFO:运送中 2019-07-15 00:22 快件在【乌鲁木齐总集散中心】已装车,准备发往 【乌鲁木齐集散中心】
26-33-2019 00:33:03 15Scends:INFO:运送中 2019-07-14 23:29 快件到达 【乌鲁木齐总集散中心】
26-33-2019 00:33:03 15Scends:INFO:落地 2019-07-14 20:34 快件到达【乌鲁木齐】，准备发往【乌鲁木齐总集散中心】
26-33-2019 00:33:03 15Scends:INFO:起飞 2019-07-14 15:49 快件在【广州飞往乌鲁木齐航班上】已起飞
26-33-2019 00:33:03 15Scends:INFO:运送中 2019-07-14 04:28 快件在【广州总集散中心】已装车,准备发往 【乌鲁木齐总集散中心】
26-33-2019 00:33:03 15Scends:INFO:运送中 2019-07-14 02:35 快件到达 【广州总集散中心】
26-33-2019 00:33:03 15Scends:INFO:运送中 2019-07-14 01:31 快件已发车
26-33-2019 00:33:03 15Scends:INFO:运送中 2019-07-14 01:31 快件在【广州新塘集散中心】已装车,准备发往 【广州总集散中心】
26-33-2019 00:33:03 15Scends:INFO:运送中 2019-07-13 23:06 快件到达 【广州新塘集散中心】
26-33-2019 00:33:03 15Scends:INFO:运送中 2019-07-13 21:53 快件已发车
26-33-2019 00:33:03 15Scends:INFO:运送中 2019-07-13 20:50 快件在【广州天河龙洞北路营业部】已装车,准备发往 【广州新塘集散中心】
26-33-2019 00:33:03 15Scends:INFO:已取件 2019-07-13 19:13 顺丰速运 已收取快件
26-33-2019 00:33:03 15Scends:INFO:正在获取电子存单信息和截图
26-33-2019 00:33:03 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 398, in get_dzcg_info
    '//div[@class="operates-wrapper"]/a').click()
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="operates-wrapper"]/a

26-33-2019 00:33:03 15Scends:INFO:该单号对应的手机号与扫码的微信号可能不符，无法获取电子存根截图
26-33-2019 00:33:03 15Scends:INFO:正在为截图添加水印
26-33-2019 00:33:03 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 422, in add_watermark
    self.__watermark(self.screenshot_img2)
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 115, in __watermark
    im = Image.open(imageFile)
  File "C:\Program Files\Python36\lib\site-packages\PIL\Image.py", line 2634, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\python_wwcheng\\sf_express\\Output\\2019-07-26 00-27-07\\img\\12-dzcg-349247356730.png'
26-33-2019 00:33:03 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 430, in next_bill_number
    '//button[@class="close"]').click()
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //button[@class="close"]

26-33-2019 00:33:05 15Scends:INFO:单号 349247356730  用时 25.997217893600464秒
26-33-2019 00:33:05 15Scends:INFO:将物流节点和电子存根信息写入csv

26-33-2019 00:33:05 15Scends:INFO:当前进度：13/18
26-33-2019 00:33:05 15Scends:INFO:正在查询的物流单号：233441276116
26-33-2019 00:33:05 15Scends:INFO:正在输入单号进行查询
26-33-2019 00:33:09 15Scends:INFO:尝试解析滑动验证码
26-33-2019 00:33:10 15Scends:INFO:解析成功，正在模拟滑动验证码・・・
26-33-2019 00:33:20 15Scends:INFO:尝试刷新验证码
26-33-2019 00:33:22 15Scends:INFO:尝试解析滑动验证码
26-33-2019 00:33:23 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 280, in get_verify_img
    img = self.browser.find_element_by_xpath('//img[@id="slideBkg"]')
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: TypeError: can't access dead object

26-33-2019 00:33:24 15Scends:INFO:解析成功，正在模拟滑动验证码・・・
26-33-2019 00:33:24 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 152, in __reload_verify_img
    self.move_slider()
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 337, in move_slider
    '//div[@id="tcaptcha_drag_button"]')
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: TypeError: can't access dead object

26-33-2019 00:33:25 15Scends:INFO:获取物流节点信息和截图
26-33-2019 00:33:27 15Scends:INFO:运送中 2019-07-16 14:13 [两河口支局]在 汉中市 已签收,本人签收 :王佳宇,投递员:张军:18329661822
26-33-2019 00:33:27 15Scends:INFO:运送中 2019-07-15 15:57 【两河口支局】投递结果反馈-未妥投,备注(其他 ),投递员:张军:18329661822
26-33-2019 00:33:27 15Scends:INFO:运送中 2019-07-15 10:32 到达【两河口支局】
26-33-2019 00:33:27 15Scends:INFO:运送中 2019-07-15 08:35 【两河口支局】安排投递,投递员:张军:18329661822
26-33-2019 00:33:27 15Scends:INFO:运送中 2019-07-13 12:52 离开【略阳寄递】,下一站【两河口支局】
26-33-2019 00:33:27 15Scends:INFO:运送中 2019-07-13 12:30 到达【略阳寄递】
26-33-2019 00:33:27 15Scends:INFO:运送中 2019-07-13 12:03 离开【中国邮政集团公司汉中市略阳县寄递事业部】,下一站【略阳处理】
26-33-2019 00:33:27 15Scends:INFO:运送中 2019-07-13 09:01 汉中市 【中国邮政集团公司汉中市略阳县寄递事业部】已收件,揽投员:高丽霞13008462300
26-33-2019 00:33:27 15Scends:INFO:运送中 2019-07-12 11:33 快件转寄【EMS】, 单号【9661052919944】,转寄的寄递信息为第三方信息方提供
26-33-2019 00:33:28 15Scends:INFO:运送中 2019-07-12 11:33 快件已转寄
26-33-2019 00:33:28 15Scends:INFO:派送中 2019-07-12 08:00 快件派送不成功（因无法满足客户派件需求），待进一步处理
26-33-2019 00:33:28 15Scends:INFO:运送中 2019-07-12 07:54 快件到达 【汉中略阳陈家沟速运营业点】
26-33-2019 00:33:28 15Scends:INFO:运送中 2019-07-12 05:56 快件已发车
26-33-2019 00:33:28 15Scends:INFO:运送中 2019-07-12 05:56 快件在【汉中汉台集散点】已装车,准备发往 【汉中略阳陈家沟速运营业点】
26-33-2019 00:33:28 15Scends:INFO:运送中 2019-07-12 04:15 快件到达 【汉中汉台集散点】
26-33-2019 00:33:28 15Scends:INFO:运送中 2019-07-11 23:23 快件已发车
26-33-2019 00:33:28 15Scends:INFO:运送中 2019-07-11 21:22 快件在【西安总集散中心】已装车,准备发往 【汉中汉台集散点】
26-33-2019 00:33:28 15Scends:INFO:运送中 2019-07-11 14:21 快件到达 【西安总集散中心】
26-33-2019 00:33:28 15Scends:INFO:落地 2019-07-11 12:47 快件到达【西安】，准备发往【西安总集散中心】
26-33-2019 00:33:28 15Scends:INFO:起飞 2019-07-11 07:16 快件在【厦门飞往西安航班上】已起飞
26-33-2019 00:33:28 15Scends:INFO:运送中 2019-07-11 01:57 快件在【厦门总集散中心】已装车,准备发往 【西安总集散中心】
26-33-2019 00:33:28 15Scends:INFO:运送中 2019-07-11 01:24 快件到达 【厦门总集散中心】
26-33-2019 00:33:28 15Scends:INFO:运送中 2019-07-11 00:12 快件已发车
26-33-2019 00:33:28 15Scends:INFO:运送中 2019-07-10 19:58 快件在【泉州晋江集散中心】已装车,准备发往 【厦门总集散中心】
26-33-2019 00:33:28 15Scends:INFO:运送中 2019-07-10 18:57 快件到达 【泉州晋江集散中心】
26-33-2019 00:33:28 15Scends:INFO:运送中 2019-07-10 17:32 快件已发车
26-33-2019 00:33:28 15Scends:INFO:运送中 2019-07-10 15:33 快件在【泉州市大客户项目营业部】已装车,准备发往 【晋江西滨跃进路营业点】
26-33-2019 00:33:28 15Scends:INFO:已揽收 2019-07-10 15:28 顺丰速运 已收取快件
26-33-2019 00:33:28 15Scends:INFO:正在获取电子存单信息和截图
26-33-2019 00:33:28 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 398, in get_dzcg_info
    '//div[@class="operates-wrapper"]/a').click()
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="operates-wrapper"]/a

26-33-2019 00:33:28 15Scends:INFO:该单号对应的手机号与扫码的微信号可能不符，无法获取电子存根截图
26-33-2019 00:33:28 15Scends:INFO:正在为截图添加水印
26-33-2019 00:33:28 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 422, in add_watermark
    self.__watermark(self.screenshot_img2)
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 115, in __watermark
    im = Image.open(imageFile)
  File "C:\Program Files\Python36\lib\site-packages\PIL\Image.py", line 2634, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\python_wwcheng\\sf_express\\Output\\2019-07-26 00-27-07\\img\\13-dzcg-233441276116.png'
26-33-2019 00:33:28 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 430, in next_bill_number
    '//button[@class="close"]').click()
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //button[@class="close"]

26-33-2019 00:33:29 15Scends:INFO:单号 233441276116  用时 24.33295702934265秒
26-33-2019 00:33:29 15Scends:INFO:将物流节点和电子存根信息写入csv

26-33-2019 00:33:30 15Scends:INFO:当前进度：14/18
26-33-2019 00:33:30 15Scends:INFO:正在查询的物流单号：SF1002139455289
26-33-2019 00:33:30 15Scends:INFO:正在输入单号进行查询
26-33-2019 00:33:33 15Scends:INFO:尝试解析滑动验证码
26-33-2019 00:33:35 15Scends:INFO:解析成功，正在模拟滑动验证码・・・
26-33-2019 00:33:46 15Scends:INFO:尝试刷新验证码
26-33-2019 00:33:48 15Scends:INFO:尝试解析滑动验证码
26-33-2019 00:33:49 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 280, in get_verify_img
    img = self.browser.find_element_by_xpath('//img[@id="slideBkg"]')
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: TypeError: can't access dead object

26-33-2019 00:33:49 15Scends:INFO:解析成功，正在模拟滑动验证码・・・
26-33-2019 00:33:49 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 152, in __reload_verify_img
    self.move_slider()
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 337, in move_slider
    '//div[@id="tcaptcha_drag_button"]')
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: TypeError: can't access dead object

26-33-2019 00:33:50 15Scends:INFO:获取物流节点信息和截图
26-33-2019 00:33:52 15Scends:INFO:已签收 2019-07-15 08:53 代签收(曹志平 ),感谢使用顺丰,期待再次为您服务
26-33-2019 00:33:52 15Scends:INFO:派送中 2019-07-15 08:06 快件交给蒋田波，正在派送途中（联系电话：15886508081）
26-33-2019 00:33:52 15Scends:INFO:运送中 2019-07-15 01:59 快件到达 【深圳坪山新区坪环街道营业部】
26-33-2019 00:33:52 15Scends:INFO:运送中 2019-07-15 01:02 快件已发车
26-33-2019 00:33:52 15Scends:INFO:运送中 2019-07-15 01:01 快件在【深圳五和集散中心】已装车,准备发往 【深圳坪山新区坪环街道营业部】
26-33-2019 00:33:52 15Scends:INFO:运送中 2019-07-14 18:50 快件到达 【深圳五和集散中心】
26-33-2019 00:33:52 15Scends:INFO:运送中 2019-07-14 16:40 快件已发车
26-33-2019 00:33:52 15Scends:INFO:运送中 2019-07-14 16:26 快件在【广州新塘集散中心】已装车,准备发往 【深圳五和集散中心】
26-33-2019 00:33:52 15Scends:INFO:运送中 2019-07-14 15:26 快件到达 【广州新塘集散中心】
26-33-2019 00:33:52 15Scends:INFO:运送中 2019-07-14 14:25 快件已发车
26-33-2019 00:33:52 15Scends:INFO:运送中 2019-07-14 14:15 快件在【广州白云萧岗明珠北路营业部】已装车,准备发往 【广州新塘集散中心】
26-33-2019 00:33:52 15Scends:INFO:已取件 2019-07-14 11:15 顺丰速运 已收取快件
26-33-2019 00:33:52 15Scends:INFO:正在获取电子存单信息和截图
26-33-2019 00:33:52 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 398, in get_dzcg_info
    '//div[@class="operates-wrapper"]/a').click()
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="operates-wrapper"]/a

26-33-2019 00:33:52 15Scends:INFO:该单号对应的手机号与扫码的微信号可能不符，无法获取电子存根截图
26-33-2019 00:33:52 15Scends:INFO:正在为截图添加水印
26-33-2019 00:33:53 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 422, in add_watermark
    self.__watermark(self.screenshot_img2)
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 115, in __watermark
    im = Image.open(imageFile)
  File "C:\Program Files\Python36\lib\site-packages\PIL\Image.py", line 2634, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\python_wwcheng\\sf_express\\Output\\2019-07-26 00-27-07\\img\\14-dzcg-SF1002139455289.png'
26-33-2019 00:33:53 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 430, in next_bill_number
    '//button[@class="close"]').click()
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //button[@class="close"]

26-33-2019 00:33:54 15Scends:INFO:单号 SF1002139455289  用时 24.922394514083862秒
26-33-2019 00:33:54 15Scends:INFO:将物流节点和电子存根信息写入csv

26-33-2019 00:33:54 15Scends:INFO:当前进度：15/18
26-33-2019 00:33:54 15Scends:INFO:正在查询的物流单号：306306249896
26-33-2019 00:33:54 15Scends:INFO:正在输入单号进行查询
26-33-2019 00:33:59 15Scends:INFO:尝试解析滑动验证码
26-34-2019 00:34:02 15Scends:INFO:解析成功，正在模拟滑动验证码・・・
26-34-2019 00:34:11 15Scends:INFO:尝试刷新验证码
26-34-2019 00:34:13 15Scends:INFO:尝试解析滑动验证码
26-34-2019 00:34:14 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 280, in get_verify_img
    img = self.browser.find_element_by_xpath('//img[@id="slideBkg"]')
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: TypeError: can't access dead object

26-34-2019 00:34:15 15Scends:INFO:解析成功，正在模拟滑动验证码・・・
26-34-2019 00:34:15 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 152, in __reload_verify_img
    self.move_slider()
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 337, in move_slider
    '//div[@id="tcaptcha_drag_button"]')
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: TypeError: can't access dead object

26-34-2019 00:34:16 15Scends:INFO:获取物流节点信息和截图
26-34-2019 00:34:18 15Scends:INFO:已签收 2019-07-15 09:38 已签收,感谢使用顺丰,期待再次为您服务
26-34-2019 00:34:18 15Scends:INFO:派送中 2019-07-15 07:21 快件交给石志强，正在派送途中（联系电话：15089248716）
26-34-2019 00:34:18 15Scends:INFO:运送中 2019-07-15 06:51 快件到达 【惠州市惠城区惠台速运营业点】
26-34-2019 00:34:18 15Scends:INFO:运送中 2019-07-15 06:28 快件已发车
26-34-2019 00:34:18 15Scends:INFO:运送中 2019-07-15 02:54 快件在【惠州陈江集散中心】已装车,准备发往 【惠州市惠城区惠台速运营业点】
26-34-2019 00:34:18 15Scends:INFO:运送中 2019-07-14 16:01 快件到达 【惠州陈江集散中心】
26-34-2019 00:34:18 15Scends:INFO:运送中 2019-07-14 14:05 快件已发车
26-34-2019 00:34:18 15Scends:INFO:运送中 2019-07-14 13:49 快件在【深圳集散中心】已装车,准备发往 【惠州陈江集散中心】
26-34-2019 00:34:18 15Scends:INFO:运送中 2019-07-14 12:46 快件到达 【深圳集散中心】
26-34-2019 00:34:18 15Scends:INFO:运送中 2019-07-14 00:06 快件已发车
26-34-2019 00:34:18 15Scends:INFO:运送中 2019-07-13 21:20 快件在【长沙星沙集散中心】已装车,准备发往 【深圳集散中心】
26-34-2019 00:34:18 15Scends:INFO:运送中 2019-07-13 21:13 快件到达 【长沙星沙集散中心】
26-34-2019 00:34:19 15Scends:INFO:运送中 2019-07-13 19:33 快件已发车
26-34-2019 00:34:19 15Scends:INFO:运送中 2019-07-13 17:12 快件在【株洲醴陵渌江大道营业点】已装车,准备发往 【长沙星沙集散中心】
26-34-2019 00:34:19 15Scends:INFO:已取件 2019-07-13 13:07 顺丰速运 已收取快件
26-34-2019 00:34:19 15Scends:INFO:运送中 2019-07-13 11:28 顺丰合作点【白兔潭镇日喜便利店】已代收
26-34-2019 00:34:19 15Scends:INFO:正在获取电子存单信息和截图
26-34-2019 00:34:19 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 398, in get_dzcg_info
    '//div[@class="operates-wrapper"]/a').click()
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="operates-wrapper"]/a

26-34-2019 00:34:19 15Scends:INFO:该单号对应的手机号与扫码的微信号可能不符，无法获取电子存根截图
26-34-2019 00:34:19 15Scends:INFO:正在为截图添加水印
26-34-2019 00:34:19 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 422, in add_watermark
    self.__watermark(self.screenshot_img2)
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 115, in __watermark
    im = Image.open(imageFile)
  File "C:\Program Files\Python36\lib\site-packages\PIL\Image.py", line 2634, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\python_wwcheng\\sf_express\\Output\\2019-07-26 00-27-07\\img\\15-dzcg-306306249896.png'
26-34-2019 00:34:19 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 430, in next_bill_number
    '//button[@class="close"]').click()
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //button[@class="close"]

26-34-2019 00:34:20 15Scends:INFO:单号 306306249896  用时 25.673138856887817秒
26-34-2019 00:34:20 15Scends:INFO:将物流节点和电子存根信息写入csv

26-34-2019 00:34:20 15Scends:INFO:已经获取15个物流信息，休息2分钟再继续
26-36-2019 00:36:20 15Scends:INFO:当前进度：16/18
26-36-2019 00:36:20 15Scends:INFO:正在查询的物流单号：349342485986
26-36-2019 00:36:20 15Scends:INFO:正在输入单号进行查询
26-36-2019 00:36:24 15Scends:INFO:尝试解析滑动验证码
26-36-2019 00:36:26 15Scends:INFO:解析成功，正在模拟滑动验证码・・・
26-36-2019 00:36:36 15Scends:INFO:尝试刷新验证码
26-36-2019 00:36:37 15Scends:INFO:尝试解析滑动验证码
26-36-2019 00:36:38 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 280, in get_verify_img
    img = self.browser.find_element_by_xpath('//img[@id="slideBkg"]')
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: TypeError: can't access dead object

26-36-2019 00:36:38 15Scends:INFO:解析成功，正在模拟滑动验证码・・・
26-36-2019 00:36:38 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 152, in __reload_verify_img
    self.move_slider()
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 337, in move_slider
    '//div[@id="tcaptcha_drag_button"]')
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: TypeError: can't access dead object

26-36-2019 00:36:40 15Scends:INFO:获取物流节点信息和截图
26-36-2019 00:36:42 15Scends:INFO:已签收 2019-07-15 11:20 已签收,感谢使用顺丰,期待再次为您服务
26-36-2019 00:36:42 15Scends:INFO:派送中 2019-07-15 11:18 快件交给尤川，正在派送途中（联系电话：13312638018）
26-36-2019 00:36:42 15Scends:INFO:派送中 2019-07-15 11:17 正在派送途中,请您准备签收(派件人:尤川,电话:13312638018)
26-36-2019 00:36:42 15Scends:INFO:派送中 2019-07-15 10:44 收方客户要求自取快件,待自取
26-36-2019 00:36:42 15Scends:INFO:运送中 2019-07-15 10:43 收方客户要求自取快件,待自取
26-36-2019 00:36:42 15Scends:INFO:派送中 2019-07-15 07:53 快件交给尤川，正在派送途中（联系电话：13312638018）
26-36-2019 00:36:42 15Scends:INFO:运送中 2019-07-15 07:12 快件到达 【曲靖麒麟瑞和新城营业点】
26-36-2019 00:36:42 15Scends:INFO:运送中 2019-07-15 06:47 快件已发车
26-36-2019 00:36:42 15Scends:INFO:运送中 2019-07-15 05:09 快件在【曲靖麒麟集散点】已装车,准备发往 【曲靖麒麟瑞和新城营业点】
26-36-2019 00:36:42 15Scends:INFO:运送中 2019-07-14 23:27 快件到达 【曲靖麒麟集散点】
26-36-2019 00:36:42 15Scends:INFO:运送中 2019-07-14 19:57 快件已发车
26-36-2019 00:36:42 15Scends:INFO:运送中 2019-07-14 19:56 快件在【昆明王家营集散中心】已装车,准备发往 【昆明临时中转场】
26-36-2019 00:36:42 15Scends:INFO:运送中 2019-07-14 19:00 快件到达 【昆明王家营集散中心】
26-36-2019 00:36:42 15Scends:INFO:运送中 2019-07-14 17:54 快件已发车
26-36-2019 00:36:42 15Scends:INFO:运送中 2019-07-14 17:20 快件在【昆明盘龙新迎小区营业点】已装车,准备发往 【昆明市盘龙区灵光街营业点】
26-36-2019 00:36:42 15Scends:INFO:已取件 2019-07-14 14:40 顺丰速运 已收取快件
26-36-2019 00:36:42 15Scends:INFO:正在获取电子存单信息和截图
26-36-2019 00:36:42 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 398, in get_dzcg_info
    '//div[@class="operates-wrapper"]/a').click()
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="operates-wrapper"]/a

26-36-2019 00:36:42 15Scends:INFO:该单号对应的手机号与扫码的微信号可能不符，无法获取电子存根截图
26-36-2019 00:36:42 15Scends:INFO:正在为截图添加水印
26-36-2019 00:36:42 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 422, in add_watermark
    self.__watermark(self.screenshot_img2)
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 115, in __watermark
    im = Image.open(imageFile)
  File "C:\Program Files\Python36\lib\site-packages\PIL\Image.py", line 2634, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\python_wwcheng\\sf_express\\Output\\2019-07-26 00-27-07\\img\\16-dzcg-349342485986.png'
26-36-2019 00:36:42 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 430, in next_bill_number
    '//button[@class="close"]').click()
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //button[@class="close"]

26-36-2019 00:36:43 15Scends:INFO:单号 349342485986  用时 22.79661250114441秒
26-36-2019 00:36:43 15Scends:INFO:将物流节点和电子存根信息写入csv

26-36-2019 00:36:43 15Scends:INFO:当前进度：17/18
26-36-2019 00:36:43 15Scends:INFO:正在查询的物流单号：283850627581
26-36-2019 00:36:43 15Scends:INFO:正在输入单号进行查询
26-36-2019 00:36:47 15Scends:INFO:尝试解析滑动验证码
26-36-2019 00:36:49 15Scends:INFO:解析成功，正在模拟滑动验证码・・・
26-36-2019 00:36:59 15Scends:INFO:尝试刷新验证码
26-37-2019 00:37:01 15Scends:INFO:尝试解析滑动验证码
26-37-2019 00:37:02 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 280, in get_verify_img
    img = self.browser.find_element_by_xpath('//img[@id="slideBkg"]')
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: TypeError: can't access dead object

26-37-2019 00:37:02 15Scends:INFO:解析成功，正在模拟滑动验证码・・・
26-37-2019 00:37:02 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 152, in __reload_verify_img
    self.move_slider()
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 337, in move_slider
    '//div[@id="tcaptcha_drag_button"]')
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: TypeError: can't access dead object

26-37-2019 00:37:03 15Scends:INFO:获取物流节点信息和截图
26-37-2019 00:37:04 15Scends:INFO:已签收 2019-07-16 10:43 代签收(装备室 ),感谢使用顺丰,期待再次为您服务
26-37-2019 00:37:04 15Scends:INFO:派送中 2019-07-16 08:43 快件交给高庆义，正在派送途中（联系电话：13522246802）
26-37-2019 00:37:05 15Scends:INFO:派送中 2019-07-16 08:42 快件交给耿纪友，正在派送途中（联系电话：18001028394）
26-37-2019 00:37:05 15Scends:INFO:运送中 2019-07-16 07:36 快件到达 【北京海淀科贸营业点】
26-37-2019 00:37:05 15Scends:INFO:运送中 2019-07-16 05:58 快件已发车
26-37-2019 00:37:05 15Scends:INFO:运送中 2019-07-16 02:05 快件在【北京南法信中转场】已装车,准备发往 【北京海淀科贸营业点】
26-37-2019 00:37:05 15Scends:INFO:运送中 2019-07-16 00:50 快件到达 【北京南法信中转场】
26-37-2019 00:37:05 15Scends:INFO:运送中 2019-07-16 00:44 快件已发车
26-37-2019 00:37:05 15Scends:INFO:运送中 2019-07-16 00:05 快件在【北京顺义集散中心】已装车,准备发往 【北京南法信中转场】
26-37-2019 00:37:05 15Scends:INFO:运送中 2019-07-15 23:24 快件到达 【北京顺义集散中心】
26-37-2019 00:37:05 15Scends:INFO:运送中 2019-07-15 06:06 快件已发车
26-37-2019 00:37:05 15Scends:INFO:运送中 2019-07-15 04:56 快件在【西北枢纽分拨中心】已装车,准备发往 【北京马驹桥集散中心】
26-37-2019 00:37:05 15Scends:INFO:运送中 2019-07-15 03:43 快件到达 【西北枢纽分拨中心】
26-37-2019 00:37:05 15Scends:INFO:运送中 2019-07-14 21:50 快件已发车
26-37-2019 00:37:05 15Scends:INFO:运送中 2019-07-14 20:14 快件在【天水麦积集散点】已装车,准备发往 【西北枢纽分拨中心】
26-37-2019 00:37:05 15Scends:INFO:运送中 2019-07-14 20:10 快件到达 【天水麦积集散点】
26-37-2019 00:37:05 15Scends:INFO:运送中 2019-07-14 17:41 快件已发车
26-37-2019 00:37:05 15Scends:INFO:运送中 2019-07-14 17:11 快件在【陇南市成县支旗村营业点】已装车,准备发往 【陇南市成县支旗村营业点】
26-37-2019 00:37:05 15Scends:INFO:已取件 2019-07-14 11:54 顺丰速运 已收取快件
26-37-2019 00:37:05 15Scends:INFO:正在获取电子存单信息和截图
26-37-2019 00:37:05 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 398, in get_dzcg_info
    '//div[@class="operates-wrapper"]/a').click()
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="operates-wrapper"]/a

26-37-2019 00:37:05 15Scends:INFO:该单号对应的手机号与扫码的微信号可能不符，无法获取电子存根截图
26-37-2019 00:37:05 15Scends:INFO:正在为截图添加水印
26-37-2019 00:37:05 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 422, in add_watermark
    self.__watermark(self.screenshot_img2)
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 115, in __watermark
    im = Image.open(imageFile)
  File "C:\Program Files\Python36\lib\site-packages\PIL\Image.py", line 2634, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\python_wwcheng\\sf_express\\Output\\2019-07-26 00-27-07\\img\\17-dzcg-283850627581.png'
26-37-2019 00:37:05 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 430, in next_bill_number
    '//button[@class="close"]').click()
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //button[@class="close"]

26-37-2019 00:37:07 15Scends:INFO:单号 283850627581  用时 24.068943977355957秒
26-37-2019 00:37:07 15Scends:INFO:将物流节点和电子存根信息写入csv

26-37-2019 00:37:07 15Scends:INFO:当前进度：18/18
26-37-2019 00:37:07 15Scends:INFO:正在查询的物流单号：368657929782
26-37-2019 00:37:07 15Scends:INFO:正在输入单号进行查询
26-37-2019 00:37:12 15Scends:INFO:尝试解析滑动验证码
26-37-2019 00:37:13 15Scends:INFO:解析成功，正在模拟滑动验证码・・・
26-37-2019 00:37:24 15Scends:INFO:尝试刷新验证码
26-37-2019 00:37:25 15Scends:INFO:尝试解析滑动验证码
26-37-2019 00:37:26 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 280, in get_verify_img
    img = self.browser.find_element_by_xpath('//img[@id="slideBkg"]')
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: TypeError: can't access dead object

26-37-2019 00:37:27 15Scends:INFO:解析成功，正在模拟滑动验证码・・・
26-37-2019 00:37:27 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 152, in __reload_verify_img
    self.move_slider()
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 337, in move_slider
    '//div[@id="tcaptcha_drag_button"]')
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: TypeError: can't access dead object

26-37-2019 00:37:28 15Scends:INFO:获取物流节点信息和截图
26-37-2019 00:37:30 15Scends:INFO:已签收 2019-07-14 18:09 已签收,感谢使用顺丰,期待再次为您服务
26-37-2019 00:37:30 15Scends:INFO:派送中 2019-07-14 17:28 快件交给王超，正在派送途中（联系电话：13699177849）
26-37-2019 00:37:30 15Scends:INFO:运送中 2019-07-14 16:34 快件到达 【庞各庄速运营业点】
26-37-2019 00:37:30 15Scends:INFO:运送中 2019-07-14 14:38 快件已发车
26-37-2019 00:37:30 15Scends:INFO:运送中 2019-07-14 14:07 快件在【北京顺义集散中心】已装车,准备发往 【庞各庄速运营业点】
26-37-2019 00:37:30 15Scends:INFO:运送中 2019-07-14 11:59 快件到达 【北京顺义集散中心】
26-37-2019 00:37:30 15Scends:INFO:运送中 2019-07-14 11:44 快件已发车
26-37-2019 00:37:30 15Scends:INFO:运送中 2019-07-14 11:39 快件在【北京国航集散中心】已装车,准备发往 【北京顺义集散中心】
26-37-2019 00:37:30 15Scends:INFO:运送中 2019-07-14 11:39 快件到达 【北京国航集散中心】
26-37-2019 00:37:30 15Scends:INFO:落地 2019-07-14 09:52 快件到达【北京】，准备发往【北京国航集散中心】
26-37-2019 00:37:30 15Scends:INFO:起飞 2019-07-14 07:45 快件在【长沙飞往北京航班上】已起飞
26-37-2019 00:37:30 15Scends:INFO:运送中 2019-07-14 01:34 快件在【长沙星沙集散中心】已装车,准备发往 【北京国航集散中心】
26-37-2019 00:37:30 15Scends:INFO:已取件 2019-07-13 15:46 顺丰速运 已收取快件
26-37-2019 00:37:30 15Scends:INFO:正在获取电子存单信息和截图
26-37-2019 00:37:30 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 398, in get_dzcg_info
    '//div[@class="operates-wrapper"]/a').click()
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="operates-wrapper"]/a

26-37-2019 00:37:30 15Scends:INFO:该单号对应的手机号与扫码的微信号可能不符，无法获取电子存根截图
26-37-2019 00:37:30 15Scends:INFO:正在为截图添加水印
26-37-2019 00:37:30 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 422, in add_watermark
    self.__watermark(self.screenshot_img2)
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 115, in __watermark
    im = Image.open(imageFile)
  File "C:\Program Files\Python36\lib\site-packages\PIL\Image.py", line 2634, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\python_wwcheng\\sf_express\\Output\\2019-07-26 00-27-07\\img\\18-dzcg-368657929782.png'
26-37-2019 00:37:30 sf_express_error:ERROR:正在记录发生的可预见错误
Traceback (most recent call last):
  File "d:/python_wwcheng/sf_express/sf_express_15Seconds.py", line 430, in next_bill_number
    '//button[@class="close"]').click()
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //button[@class="close"]

26-37-2019 00:37:31 15Scends:INFO:单号 368657929782  用时 23.958998441696167秒
26-37-2019 00:37:31 15Scends:INFO:将物流节点和电子存根信息写入csv

26-37-2019 00:37:31 15Scends:INFO:程序总用时：624.3374059200287
